---
#- name: Check if mutt is installed
#  command: which mutt
#  ignore_errors: yes
#  register: mutt_check
#  become: yes
#  become_user: echuraev
#
- name: Install mutt packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mutt
    - isync
    - imapfilter
    - msmtp
    - notmuch
    - gawk
    - pandoc
    - urlview
    - lbdb

- name: Install mutt packages for Mac
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - terminal-notifier
  when: ansible_distribution == 'MacOSX'

# http://unixwiz.net/tools/lockrun.html

# Make some directories required by configuration in the dotfiles; these should
# probably be separate roles.
- name: Mutt - create auxiliary directories
  file: path={{ item }} state=directory
  loop:
    # mbsync will die on first sync without this:
    - ~/.mail
  become: yes
  become_user: echuraev
