---
- hosts: localhost
  # environment:
  #   http_proxy:
  #   https_proxy:
  become_user: echuraev

  roles:
    - role: packages
      become: yes
      become_user: root
    #- role: awesome
    #- become: yes
    #- become_user: root
    - role: awesome-build
      become: yes
      become_user: root
    - role: rofi-build
      become: yes
      become_user: root
    - role: user-settings
    - role: dropbox
      become: yes
      become_user: root
    #- role: vim
    #- become: yes
    #- become_user: root
    - role: vim-build
      become: yes
      become_user: root
    - role: vifm-build
      become: yes
      become_user: root
    - role: kitty
      become: yes
      become_user: root
    #- role: rxvt-unicode
    #  become: yes
    #  become_user: root
    - role: ranger
      become: yes
      become_user: root
    - role: ctags-build
      become: yes
      become_user: root
    - role: terminfo
      become: yes
      become_user: echuraev
    - role: mutt
      become: yes
      become_user: root

