---
- hosts: localhost
  # environment:
  #   http_proxy:
  #   https_proxy:
  become_user: echuraev

  roles:
    - role: packages
      become: yes
      become_user: root
    - role: awesome
      become: yes
      become_user: root
    - role: user-settings
    - role: dropbox
      become: yes
      become_user: root
    - role: vim
      become: yes
      become_user: root
    - role: rxvt-unicode
      become: yes
      become_user: root

