---
- hosts: localhost
  # environment:
  #   http_proxy:
  #   https_proxy:
  become_user: echuraev

  roles:
    - role: packages
    - role: user-settings
    - role: terminfo
    - role: ranger
    - role: ctags-build

