---
- hosts: localhost
  become_user: "{{ ansible_env.USER | default('echuraev') }}"

  roles:
    - role: packages
    #- role: awesome
    #- become: yes
    #- become_user: root
    - role: awesome-build
      become: yes
      become_user: root
    - role: rofi-build
      become: yes
      become_user: root
    - role: user-settings
    - role: dropbox
      become: yes
      become_user: root
    #- role: vim
    #- become: yes
    #- become_user: root
    - role: vim-build
      become: yes
      become_user: root
    - role: vifm-build
      become: yes
      become_user: root
    - role: kitty
      become: yes
      become_user: root
    #- role: rxvt-unicode
    #  become: yes
    #  become_user: root
    - role: mutt
    - role: ctags-build
    - role: terminfo

