---
- name: Add packages keys
  apt_key: url={{ item }} state=present
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Add packages repositories
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
      - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      - ppa:pmjdebruijn/darktable-release       # Darktable repository
      - ppa:ermshiperete/monodevelop            # Mono
      - ppa:sethj/silentcast                    # Silentcast
      - ppa:plushuang-tw/uget-stable            # Uget
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - zsh
    - curl
    - git
    - mc
    - htop
    - tmux
    - rxvt-unicode-256color
    - cmake
    - python-pip
    - openssh-server
    - google-chrome-stable
    - pavucontrol
    - x11vnc
    - tightvncserver
    - darktable
    - gimp
    - remmina
    - remmina-plugin-vnc
    - remmina-plugin-rdp
    - anki
    - mplayer
    - monodevelop-current
    - mono-xbuild
    - mono-complete
    - silentcast
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-full
    - autoconf
    - python-tk
    - python3-tk
    - uget
  become: yes
  become_user: root

- name: Upgrade pip
  pip: name=pip extra_args=--upgrade
  become: yes
  become_user: root

