---
- name: Add packages keys
  apt_key: url={{ item }} state=present
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Add packages repositories
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
      - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      - ppa:jonathonf/vim
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - zsh
    - curl
    - git
    - vim
    - mc
    - htop
    - tmux
    - cmake
    - rxvt-unicode-256color
    - python-pip
    - openssh-server
    - google-chrome-stable
  become: yes
  become_user: root

- name: Install Dropbox control script
  get_url: dest=/usr/local/bin/dropbox.py url=https://www.dropbox.com/download?dl=packages/dropbox.py mode=0755
  become: yes
  become_user: root

- name: Install Dropbox
  shell: curl -L "https://www.dropbox.com/download?plat=lnx.{{ansible_architecture}}" | tar -C $HOME -xzf - creates=$HOME/.dropbox-dist/dropboxd
  become: yes
  become_user: echuraev

- name: Check dropboxd status
  command: /usr/local/bin/dropbox.py status
  register: status
  become: yes
  become_user: echuraev

- name: Start dropboxd
  shell: /usr/local/bin/dropbox.py start >/dev/null 2>&1
  when: status.stdout == "Dropbox isn't running!"
  become: yes
  become_user: echuraev

