---
- name: Add packages keys
  apt_key: url={{ item }} state=present
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Add packages repositories
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
      - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      - ppa:pmjdebruijn/darktable-release       # Darktable repository
      - ppa:dhor/myway                          # RawTherapee
      #- ppa:ermshiperete/monodevelop            # Mono
      - ppa:sethj/silentcast                    # Silentcast
      - ppa:plushuang-tw/uget-stable            # Uget
      - ppa:git-core/ppa                        # git lfs
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Install EPEL repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root

- name: Add git lfs to apt-get install
  shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - curl
    - git
    - mc
    - htop
    - tmux
    - cmake
    - autoconf
    - automake
    - wget
    - gawk
    - gdb
    - gcc    # Need it on CentOS
    - llvm   # For autocompletion

# Some info get from here: https://developers.redhat.com/blog/2018/07/07/yum-install-gcc7-clang/
- name: Install RedHat packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - llvm-toolset-7
    - llvm-toolset-7-clang-tools-extra  # clangd
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root

- name: Install cask packages homebrew
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - mactex
    - caskroom/cask/brew-cask
    - cargo
    - buku
  when: ansible_distribution == 'MacOSX'
  become: yes
  become_user: echuraev

- name: Install Ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pkg-config
    - rxvt-unicode-256color
    - google-chrome-stable
    - pavucontrol
    - x11vnc
    - tightvncserver
    - darktable
    - rawtherapee
    - gimp
    - remmina
    - remmina-plugin-vnc
    - remmina-plugin-rdp
    - mplayer
    #- monodevelop-current
    #- mono-xbuild
    #- mono-complete
    #- silentcast
    - uget
    - git-lfs
    - python-pip
    - openssh-server
    - anki
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-full
    - python-tk
    - python3-tk
    - buku
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Upgrade pip
  pip: name=pip extra_args=--upgrade
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Install git lfs
  shell: git lfs install
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: echuraev
