---
- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - awesome
    - awesome-extra
    - zsh
    - git
    - vim
    - mc
    - tmux
    - cmake
    - python-pip
    - openssh-server
    # google-chrome
  become: yes
  become_user: root
