---
- name: Check if vifm is installed
  command: which vifm
  ignore_errors: yes
  register: vifm_check

#- name: Install Überzug for image preview
#  pip:
#    executable: pip3
#    name: ueberzug
#  when: ansible_distribution != 'MacOSX'

- name: Install vifm packages RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - fuse
    - fuseiso
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root

- name: Install vifm packages Ubuntu
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - fuse
    - fuse-zip
    - fusefat
    - fuseiso
    - libncursesw5
    - libncursesw5-dev
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Download vifm sources
  git:
    repo: 'https://github.com/vifm/vifm'
    dest: /tmp/vifm
  when: vifm_check.rc != 0

- name: Reconf on RedHat
  shell: cd /tmp/vifm && autoreconf -f -i
  when: vifm_check.rc != 0 and ansible_os_family == 'RedHat'

- name: Configure vifm
  shell: cd /tmp/vifm && ./configure --enable-extended-keys --enable-desktop-files --enable-remote-cmds
  when: vifm_check.rc != 0

- name: Make vifm
  shell: cd /tmp/vifm && make -j8
  when: vifm_check.rc != 0

- name: Make install vifm
  shell: cd /tmp/vifm && make -j8 install
  when: vifm_check.rc != 0
  become: yes
  become_user: root

