---
- name: Install Arch packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - base-devel
    - ntfs-3g
    - gnome-terminal
    - vifm
    - xorg-server
    - xorg-xinit
    - xterm
  become: yes
  become_user: root

#  Install yay {{{ #
- name: Download yay sources
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: /tmp/yay

- name: Install yay
  shell: cd /tmp/yay && makepkg -si --noconfirm && cd - && rm -rf /tmp/yay
#  }}} Install yay #
#  Enable repos {{{ #
- name: Check multilib comment
  become: yes
  become_user: root
  lineinfile:
    path: /etc/pacman.conf
    line: "#[multilib]"
    state: present
  check_mode: yes
  register: multilib_comment

- name: Enable multilib
  become: yes
  become_user: root
  when: multilib_comment is not changed
  replace:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist'
    replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'

- name: Run the equivalent of "pacman -Sy" as a separate step
  when: multilib_comment is not changed
  pacman:
    update_cache: yes
  become: yes
  become_user: root
#  }}} Enable repos #
#  Network management {{{ #
- name: Install Network management tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - networkmanager
    - network-manager-applet
  become: yes
  become_user: root

- name: Network Manager service enable
  service:
    name: NetworkManager
    enabled: yes
  become: yes
  become_user: root
#  Install networkmanager-l2tp vpn {{{ #
- name: Download networkmanager-l2tp sources
  git:
    repo: 'https://aur.archlinux.org/networkmanager-l2tp.git'
    dest: /tmp/networkmanager-l2tp

- name: Install networkmanager-l2tp
  shell: cd /tmp/networkmanager-l2tp && makepkg -si --noconfirm && cd - && rm -rf /tmp/networkmanager-l2tp
#  }}} Install networkmanager-l2tp vpn #
#  }}} Network management #
#  Drivers {{{ #
- name: Install Arch Drivers
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nvidia
    - nvidia-settings
  become: yes
  become_user: root
#  }}} Drivers #
#  LightDM {{{ #
- name: Install LightDM
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - lightdm
    - lightdm-gtk-greeter
    - numlockx
  become: yes
  become_user: root

- name: LightDM check default greeter
  become: yes
  become_user: root
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: "#greeter-session=example-gtk-gnome"
    state: present
  check_mode: yes
  register: lightdm_greeter

- name: LightDM set default greeter
  become: yes
  become_user: root
  when: lightdm_greeter is not changed
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "{{ item.From }}"
    line: "{{ item.To }}"
    state: present
  with_items:
      - { From: '^#greeter-session=example-gtk-gnome', To: 'greeter-session=lightdm-gtk-greeter' }
      - { From: '^#greeter-setup-script=', To: 'greeter-setup-script=/usr/bin/numlockx on' }

- name: LightDM service enable
  service:
    name: lightdm
    enabled: yes
  become: yes
  become_user: root
#  }}} LightDM #
#  Office {{{ #
- name: Install Arch Office packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libreoffice-still
  become: yes
  become_user: root
#  }}} Office #
#  File Manager {{{ #
- name: Install Arch File Manager
  package:
    name: "{{ item }}"
    state: present
  with_items:
    #- gvfs
    #- thunar
    #- thunar-volman
    - lxsession     # add this to autoload
    - nautilus
  become: yes
  become_user: root
#  }}} File Manager #
#  Image processing {{{ #
- name: Install Arch Image processing
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - darktable
    - digikam
    - gimp
    - inkscape
    - vimiv
  become: yes
  become_user: root
#  }}} Image processing #
#  Media & Audio {{{ #
- name: Install Arch packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    #- alsa-utils
    - pavucontrol
    - pulseaudio
    - pulseaudio-alsa
    - vlc
  become: yes
  become_user: root
#  }}} Media & Audio #
#  Internet {{{ #
- name: Install Arch packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox
  become: yes
  become_user: root
#  }}} Internet #
#  Window programs {{{ #
- name: Install Win programs support
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wine
    - steam
  become: yes
  become_user: root
#  }}} Window programs #
#  Printing {{{ #
- name: Install tools for printers
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cups
    - cups-pdf
    - system-config-printer
  become: yes
  become_user: root

- name: Enable cups service
  service:
    name: org.cups.cupsd.service
    enabled: yes
  become: yes
  become_user: root
#  }}} Printing #
#  Scanning {{{ #
- name: Install tools for scanning
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - sane
    - simple-scan
  become: yes
  become_user: root
#  }}} Scanning #

# vim: foldmethod=marker:foldlevel=0
