---
# Use to remove 'dpkg -r vim'
- stat: path=~/.bin/ranger
  register: ranger

- name: Install ranger packages Linux
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - caca-utils
    - highlight
    - atool
    - w3m
    - w3m-img
    - poppler-utils
    - mediainfo
    - odt2txt
    - ffmpegthumbnailer
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_user: root

- name: Install ranger packages Mac
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - highlight
    - atool
    - w3m
    - mediainfo
    - odt2txt
    - ffmpegthumbnailer
    - xpdf
    - libcaca
    - imlib2
    - lynx
  when: ansible_distribution == 'MacOSX'
  become: yes
  become_user: echuraev

- name: Download ranger sources
  git:
    repo: 'https://github.com/ranger/ranger'
    dest: ~/.bin/ranger-sources
  when: ranger.stat.exists == False
  become: yes
  become_user: echuraev

- name: Create symling
  shell: ln -s ~/.bin/ranger-sources/ranger.py ~/.bin/ranger
  when: ranger.stat.exists == False
  become: yes
  become_user: echuraev

