---
- stat: path=/usr/local/bin/dropbox.py
  register: dropbox_py

- stat: path=~/.dropbox-dist/dropboxd
  register: dropbox_exec

- name: Install Dropbox control script
  get_url: dest=/usr/local/bin/dropbox.py url=https://www.dropbox.com/download?dl=packages/dropbox.py mode=0755
  when: dropbox_py.stat.exists == False
  become: yes
  become_user: root

- name: Install Dropbox
  shell: curl -L "https://www.dropbox.com/download?plat=lnx.{{ansible_architecture}}" | tar -C $HOME -xzf - creates=$HOME/.dropbox-dist/dropboxd
  when: dropbox_exec.stat.exists == False

- name: Check dropboxd status
  command: /usr/local/bin/dropbox.py status
  register: status

- name: Start dropboxd
  shell: /usr/local/bin/dropbox.py start >/dev/null 2>&1
  when: status.stdout == "Dropbox isn't running!"

