---
- stat: path=~/.git
  register: git_dir

- name: Download my dotfiles
  git:
    repo: 'https://github.com/echuraev/dotfiles'
    dest: /tmp/dotfiles
  when: git_dir.stat.exists == False

- name: Install my dotfiles
  shell: /tmp/dotfiles/install.sh
  when: git_dir.stat.exists == False

- name: Remove tmp files
  file:
    state: absent
    path: "/tmp/dotfiles/"
  when: git_dir.stat.exists == False

- stat: path="/usr/share/fonts/Literation Mono Powerline Nerd Font Complete Mono.ttf"
  when: ansible_distribution != 'MacOSX'
  register: lin_font_installed

- stat: path="/usr/share/fonts/Literation Mono Powerline Nerd Font Complete Mono.ttf"
  when: ansible_distribution == 'MacOSX'
  register: mac_font_installed

- name: Install font
  get_url: dest="/usr/share/fonts/Literation Mono Powerline Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
  when: ansible_distribution != 'MacOSX' and lin_font_installed.stat.exists == False
  become: yes
  become_user: root

- name: Install font
  get_url: dest="~/Library/Fonts/Literation Mono Powerline Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
  when: ansible_distribution == 'MacOSX' and mac_font_installed.stat.exists == False

- name: Set zsh as default shell for user
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become_user: root
  become: yes

