---
- name: Install VIM packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev
    - vim
    - libx11-dev
    - libxkbfile-dev
  become: yes
  become_user: root
