---
# Use to remove 'dpkg -r vim'
- name: Check if vim is installed
  command: which vim
  ignore_errors: yes
  register: vim_check
  become: yes
  become_user: echuraev

- name: Install VIM packages RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - lua-devel
    - luajit
    - luajit-devel
    - ruby-devel
    - perl-devel
    - ncurses-devel
    - libgnome-devel
    - gtk2-devel
    - atk-devel
    - libX11-devel
    - libXpm-devel
    - libXt-devel
    - python-devel
    - python36-devel
    - libxkbfile-devel
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root

- name: Install VIM packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - liblua5.1-dev
    - luajit
    - libluajit-5.1-dev
    - python-dev
    - ruby-dev
    - libperl-dev
    - libncurses5-dev
    - libgnome2-dev
    - libgtk2.0-dev
    - libatk1.0-dev
    - libx11-dev
    - libxpm-dev
    - libxt-dev
    - python-dev
    - python2.7-dev
    - python3-dev
    - libxkbfile-dev
    - checkinstall
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Download vim sources
  git:
    repo: 'https://github.com/vim/vim'
    dest: /tmp/vim
  when: vim_check.rc != 0
  become: yes
  become_user: echuraev

- name: Configure vim Linux
  shell: cd /tmp/vim && ./configure --with-features=huge \
                                    --enable-multibyte \
                                    --enable-rubyinterp=dynamic \
                                    --with-ruby-command=$(which ruby) \
                                    --enable-pythoninterp=yes \
                                    --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
                                    --enable-python3interp=yes \
                                    --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
                                    --enable-perlinterp=dynamic \
                                    --enable-luainterp \
                                    --with-luajit \
                                    --enable-cscope \
                                    --with-x \
                                    --enable-gui=auto \
                                    --enable-gtk2-check \
                                    --enable-gnome-check \
                                    --enable-fontset \
                                    --enable-largefile \
                                    --with-compiledby="echuraev" \
                                    --enable-fail-if-missing \
                                    --prefix=/usr/local
  when: vim_check.rc != 0 and (ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian')
  become: yes
  become_user: echuraev

- name: Configure vim RedHat
  shell: cd /tmp/vim && ./configure --with-features=huge \
                                    --enable-multibyte \
                                    --enable-rubyinterp=dynamic \
                                    --with-ruby-command=$(which ruby) \
                                    --enable-pythoninterp=yes \
                                    --with-python-config-dir=/usr/lib64/python2.7/config \
                                    --enable-python3interp=yes \
                                    --with-python3-config-dir=/usr/lib64/python3.6/config \
                                    --enable-luainterp \
                                    --with-luajit \
                                    --enable-cscope \
                                    --with-x \
                                    --enable-gui=auto \
                                    --enable-gtk2-check \
                                    --enable-gnome-check \
                                    --enable-fontset \
                                    --enable-largefile \
                                    --with-compiledby="echuraev" \
                                    --enable-fail-if-missing \
                                    --prefix=/usr/local
  when: vim_check.rc != 0 and ansible_os_family == 'RedHat'
  become: yes
  become_user: echuraev

# Config directory should contain config.c file
#
# Had a problem with YCM and python@2. Use system python2.7.
# 1. Run: brew uninstall python@2
# 2. Install ansible using pip
# 3. Run ansible script
- name: Configure vim Mac
  shell: cd /tmp/vim && ./configure --with-features=huge \
                                    --enable-multibyte \
                                    --enable-rubyinterp=dynamic \
                                    --with-ruby-command=$(which ruby) \
                                    --enable-pythoninterp=yes \
                                    --with-python-config-dir=/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config \
                                    --enable-python3interp=yes \
                                    --with-python3-config-dir=/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin \
                                    --enable-perlinterp=dynamic \
                                    --enable-cscope \
                                    --enable-fontset \
                                    --enable-largefile \
                                    --with-compiledby="echuraev" \
                                    --enable-fail-if-missing \
                                    --prefix=/usr/local
  when: vim_check.rc != 0 and ansible_distribution == 'MacOSX'
  become: yes
  become_user: echuraev

- name: Make vim
  shell: cd /tmp/vim && make -j8
  when: vim_check.rc != 0
  become: yes
  become_user: echuraev

- name: Make install vim
  shell: cd /tmp/vim && make install
  when: vim_check.rc != 0
  become: yes
  become_user: root

