---
#  Ubuntu {{{ #
- name: Add Awesome repository
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
    - ppa:klaus-vormweg/awesome
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Install Awesome packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - awesome
    - awesome-extra
    - xscreensaver
    - xscreensaver-gl-extra
    - xscreensaver-data-extra
    - xscreensaver-screensaver-bsod
    - xscreensaver-screensaver-webcollage
    - screengrab                              # screenshot util
    - volumeicon-alsa                         # tray sound icon
    - lua-json
    - lua-sec
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root
#  }}} Ubuntu #
#  Arch {{{ #
- name: Install Awesome packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - awesome
  when: ansible_os_family == 'Archlinux'
  become: yes
  become_user: root
#  }}} Arch #

# vim: foldmethod=marker:foldlevel=0
